%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rqt-multiplot
Version:        0.0.12
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rqt_multiplot package

License:        GNU Lesser General Public License (LGPL)
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       qt5-qtbase-devel
Requires:       qwt-qt5-devel
Requires:       ros-noetic-rosbag
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-rqt-gui
Requires:       ros-noetic-rqt-gui-cpp
Requires:       ros-noetic-variant-topic-tools
BuildRequires:  gtest-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qwt-qt5-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-rosbag
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-rqt-gui
BuildRequires:  ros-noetic-rqt-gui-cpp
BuildRequires:  ros-noetic-variant-topic-tools
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
rqt_multiplot provides a GUI plugin for visualizing numeric values in multiple
2D plots using the Qwt plotting backend.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Jan 14 2021 Samuel Bachmann <sbachmann@anybotics.com> - 0.0.12-1
- Autogenerated by Bloom

* Tue Jan 12 2021 Samuel Bachmann <sbachmann@anybotics.com> - 0.0.11-1
- Autogenerated by Bloom

