Name:           ros-melodic-rqt-multiplot
Version:        0.0.9
Release:        1%{?dist}
Summary:        ROS rqt_multiplot package

Group:          Development/Libraries
License:        GNU Lesser General Public License (LGPL)
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-rosbag
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rqt-gui
Requires:       ros-melodic-rqt-gui-cpp
Requires:       ros-melodic-variant-topic-tools
BuildRequires:  qwt-qt5-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rosbag
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rqt-gui
BuildRequires:  ros-melodic-rqt-gui-cpp
BuildRequires:  ros-melodic-variant-topic-tools

%description
rqt_multiplot provides a GUI plugin for visualizing numeric values in multiple
2D plots using the Qwt plotting backend.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Dec 13 2018 Ralf Kaestner <ralf.kaestner@gmail.com> - 0.0.9-1
- Autogenerated by Bloom

* Wed Dec 12 2018 Ralf Kaestner <ralf.kaestner@gmail.com> - 0.0.9-0
- Autogenerated by Bloom

* Mon Dec 03 2018 Ralf Kaestner <ralf.kaestner@gmail.com> - 0.0.8-1
- Autogenerated by Bloom

* Thu Nov 29 2018 Ralf Kaestner <ralf.kaestner@gmail.com> - 0.0.8-0
- Autogenerated by Bloom

